### ISSUE TITLE
Recurring TypeError with PrettyTree 

### ISSUE THREAD

**Issue by auroraab** [harmslab/topiary#48]
Hello! Thank you so much for making and maintaining this wonderful tool. I've been working through the pipeline, and while the code is able to run through the steps in ali_to_anc, I do keep getting an error that seems to be in the PrettyTree script, and the output directories do not have the pdfs with trees in them. I recreated the error on the python API by running the following: 

```
>>> topiary.draw.tree("01_gene-tree")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/home/users/auroraab/.conda/envs/topiary/lib/python3.10/site-packages/topiary/draw/tree.py", line 181, in tree
    pt = PrettyTree(T,
  File "/global/home/users/auroraab/.conda/envs/topiary/lib/python3.10/site-packages/topiary/draw/prettytree.py", line 91, in __init__
    if issubclass(type(T),toytree.tree):
TypeError: issubclass() arg 2 must be a class, a tuple of classes, or a union 
```

Am I missing a package or something? I installed everything according to the instructions... Is it a python version syntax problem? I am running Python 3.10.8 (which if I remember correctly was necessary for installing some of the accessory programs topiary uses).

Very grateful for any advice you can provide!
Aurora

**Comment by cfreye** [comment]
Hi Aurora! I ran into a similar issue and was able to resolve it by installing version 2.0.1 of toytree. Hope this helps!

**Comment by bensprung** [comment]
I ran into this same error. To install version 2.0.1 of toytree (thanks to @cfreye for the tip), I deleted my topiary environment and re-created it using the environment.yml below. I also ran into a different error that went away when I specified an older numpy, and then one more that was solved by installing raxml-ng version 1.1.0, not the current 1.2.2.

```
name: topiary
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy=1.24.0
  - pandas
  - xlrd
  - openpyxl
  - matplotlib
  - biopython
  - tqdm
  - ete3
  - dendropy
  - toytree=2.0.1
  - pastml
  #- openmpi  # [not win]
  #- blast    # [not win]
  #- muscle   # [not win]
  #- generax  # [not win]
  #- raxml-ng # [not win]
  #- mpi4py   # [not win]
  - pip
  - pip:
    - opentree
```

**Comment by harmsm** [comment]
If it's still helpful to you, we've fixed this problem. We've upgraded all the way to toytree3 and ETE4, which together are much improved and more stable. See PR #46. We're doing some final tests and will then release a new (much improved!) version of the software. 

Sorry for the (very) slow reply. We haven't had anyone to take the lead on topiary development. We should be in a much better place now to maintain this package if future issues comes up.

Best,

Mike
